name: Check Markdown links

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: "28 2 3,17 * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
