name: Check Markdown links

on:
  push:
    branches:
      - trunk
  schedule:
    - cron: "28 2 3,17 * *"

jobs:
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
